apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-service-deploy
  labels:
    app: inventory-service
spec:
  replicas: 2
  minReadySeconds: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  selector:
    matchLabels:
      app: inventory-service
  template:
    metadata:
      labels:
        app: inventory-service
    spec:
      terminationGracePeriodSeconds: 1
      containers:
        - name: inventory-service-pod
          image: anilshirole/inventory-service:1.0.0
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          env:
            - name: MONGO_URI
              value: 34.171.109.17:27017
            - name: LOG_LEVEL
              value: debug
          volumeMounts:
            - name: file-storage
              mountPath: /usr/src/app/uploads
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 3000
            initialDelaySeconds: 30
            periodSeconds: 30
      volumes:
        - name: file-storage
          persistentVolumeClaim:
            claimName: file-storage-pvc
